Including countries of each stop in Chuuchuu data

In [38]:
import pandas as pd

In [39]:
uic_codes = pd.read_csv("UIC_country_codes.csv", sep =";")
chuuchuu = pd.read_csv("delay_records_2026-02-26_to_2026-03-04.csv")

C:\Users\TE\AppData\Local\Temp\ipykernel_28936\1820012536.py:2: DtypeWarning: Columns (2,4) have mixed types. Specify dtype option on import or set low_memory=False.
  chuuchuu = pd.read_csv("delay_records_2026-02-26_to_2026-03-04.csv")

In [40]:
chuuchuu.head()

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalPlatform,plannedArrivalPlatform,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra
0,NS,Sprinter,8148,2026-02-26,8400058,2026-02-25 04:51:47+00,Sprinter 8148,2992170,Amsterdam Centraal,2026-02-26 14:25:00+00,...,10a,10a,f,NaN,2026-02-26 14:25:00+00,NaN,10a,10a,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
1,NS,Sprinter,8148,2026-02-26,8400059,2026-02-25 04:51:47+00,Sprinter 8148,2992236,Amsterdam Sloterdijk,2026-02-26 14:19:00+00,...,12,12,f,2026-02-26 14:19:00+00,2026-02-26 14:19:00+00,0.0,12,12,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
2,NS,Sprinter,8148,2026-02-26,8400561,2026-02-25 04:51:47+00,Sprinter 8148,3065389,Schiphol Airport,2026-02-26 14:07:00+00,...,3,3,f,2026-02-26 14:09:00+00,2026-02-26 14:09:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
3,NS,Sprinter,8148,2026-02-26,8400079,2026-02-25 04:51:47+00,Sprinter 8148,2860888,Amsterdam Lelylaan,2026-02-26 14:15:00+00,...,2,2,f,2026-02-26 14:15:00+00,2026-02-26 14:15:00+00,0.0,2,2,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."
4,NS,Sprinter,8148,2026-02-26,8400332,2026-02-25 04:51:47+00,Sprinter 8148,2993022,Hoofddorp,NaN,...,3,3,f,2026-02-26 14:02:00+00,2026-02-26 14:02:00+00,0.0,3,3,f,"{""nsAgency"": ""IFF:NS"", ""unplanned"": false, ""fu..."

In [41]:
chuuchuu["uicCodeStop"] = chuuchuu["deutscheBahnStopId"].astype(str).str[:2]

In [42]:
chuuchuu["uicCodeStop"].head(5)

0    84
1    84
2    84
3    84
4    84
Name: uicCodeStop, dtype: object

In [43]:
chuuchuu["uicCodeStop"] = chuuchuu["uicCodeStop"].astype(str)
uic_codes["Numerical code"] = uic_codes["Numerical code"].astype(str)

In [44]:
chuuchuu = chuuchuu.merge(
    uic_codes[["Numerical code", "Alphabetical code"]],
    how="left",                       # keep all rows in chuuchuu
    left_on="uicCodeStop",            # column in chuuchuu
    right_on="Numerical code"         # column in uic_codes
)
chuuchuu = chuuchuu.drop(columns=["Numerical code"])

In [45]:
chuuchuu = chuuchuu.rename(columns={"Alphabetical code": "countryStop"})

In [49]:
print(len(chuuchuu["countryStop"].unique()))
print(chuuchuu["countryStop"].unique())

57
['NL' 'IT' 'BE' 'DK' 'DE' 'FR' 'LU' 'CH' nan 'BA' 'TJ' 'HU' 'MK' 'ME' 'UA'
 'AT' 'AM' 'FI' 'SE' 'PL' 'KP' 'CZ' 'GB' 'IL' 'LB' 'CN' 'HR' 'RO' 'RU'
 'RS' 'KR' 'IE' 'JP' 'GR' 'IQ' 'EE' 'DZ' 'SI' 'BY' 'LT' 'IR' 'KG' 'CU'
 'GE' 'LV' 'ES' 'LA' 'EG' 'TR' 'VN' 'MA' 'SK' 'AZ' 'NO' 'TZ' 'SY' 'KZ']

In [50]:
chuuchuu[chuuchuu["countryStop"]=="BA"]

,agency,routeType,routeNumber,date,deutscheBahnStopId,timestamp,originalRoute,originalStopId,stopName,arrival,...,arrivalCancelled,departure,plannedDeparture,departureDelay,departurePlatform,plannedDeparturePlatform,departureCancelled,extra,uicCodeStop,countryStop
2363,GTFSDE,RB,10452,2026-02-26,449999,2026-02-25 23:45:45+00,RB24 10452,::stop0165826,Satzvey,2026-02-25 23:18:00+00,...,f,2026-02-25 23:19:00+00,2026-02-25 23:19:00+00,0.0,NaN,2,f,"{""unplanned"": false, ""originalTripId"": ""203390...",44,BA
4472,GTFSDE,S,33159,2026-02-26,446745,2026-02-26 00:46:15+00,S11 33159,::stop01142605,Köln-Buchforst,2026-02-25 23:37:00+00,...,f,2026-02-25 23:37:00+00,2026-02-25 23:37:00+00,0.0,NaN,2,f,"{""unplanned"": false, ""originalTripId"": ""14149""...",44,BA
5854,GTFSDE,S,33161,2026-02-26,446745,2026-02-26 01:01:15+00,S11 33161,::stop01142605,Köln-Buchforst,2026-02-26 00:08:00+00,...,f,2026-02-26 00:08:00+00,2026-02-26 00:07:00+00,60.0,NaN,2,f,"{""unplanned"": false, ""originalTripId"": ""366181...",44,BA
5871,GTFSDE,S,33165,2026-02-26,446745,2026-02-26 01:01:15+00,S11 33165,::stop01142605,Köln-Buchforst,2026-02-26 00:36:00+00,...,f,2026-02-26 00:37:00+00,2026-02-26 00:37:00+00,0.0,NaN,2,f,"{""unplanned"": false, ""originalTripId"": ""251148...",44,BA
6847,GTFSDE,S,33167,2026-02-26,446745,2026-02-26 01:31:45+00,S11 33167,::stop01142605,Köln-Buchforst,2026-02-26 01:06:00+00,...,f,2026-02-26 01:07:00+00,2026-02-26 01:07:00+00,0.0,NaN,2,f,"{""unplanned"": false, ""originalTripId"": ""211156...",44,BA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6620997,PL,IC,3810,2026-03-04,44420_1_1,2026-03-05 02:39:53+00,IC 3810 Kossak,44420_1_1,Żmigród,2026-03-04 13:36:00+00,...,f,2026-03-04 13:37:30+00,2026-03-04 13:27:30+00,600.0,1/1,1/1,f,"{""unplanned"": false, ""originalTripId"": ""2026-0...",44,BA
6620998,PL,IC,3810,2026-03-04,44305_1_1,2026-03-05 02:39:53+00,IC 3810 Kossak,44305_1_1,Rawicz,2026-03-04 13:44:30+00,...,f,2026-03-04 13:50:30+00,2026-03-04 13:37:30+00,780.0,1/1,1/1,f,"{""unplanned"": false, ""originalTripId"": ""2026-0...",44,BA
6621073,PL,IC,5222,2026-03-04,50104_2_1,2026-03-05 02:39:53+00,IC 5222 Rejewski,50104_2_1,Nałęczów,2026-03-04 16:20:30+00,...,f,2026-03-04 16:21:30+00,2026-03-04 16:09:30+00,720.0,2/1,2/1,f,"{""unplanned"": false, ""originalTripId"": ""2026-0...",50,BA
6621193,PL,IC,5224,2026-03-04,49809_2_1,2026-03-05 02:39:53+00,IC 5224 Kujawiak,49809_2_1,Dęblin,2026-03-04 11:46:00+00,...,f,2026-03-04 11:47:00+00,2026-03-04 11:46:00+00,60.0,2/1,2/1,f,"{""unplanned"": false, ""originalTripId"": ""2026-0...",49,BA
6621216,PL,IC,5226,2026-03-04,49809_2_1,2026-03-05 02:39:53+00,IC 5226 Kochanowski,49809_2_1,Dęblin,2026-03-04 07:48:00+00,...,f,2026-03-04 07:49:00+00,2026-03-04 07:46:00+00,180.0,2/1,2/1,f,"{""unplanned"": false, ""originalTripId"": ""2026-0...",49,BA